# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.52/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Graphql
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: PageColumn
          name: pageColumn
          layout:
            columnSize: 1
          children:
            - component: PageRow
              name: pageRow1
              props:
                justifyContent: start
              children:
                - component: PageColumn
                  name: pageColumn1
                  layout:
                    columnSize: 1
                  children:
                    - component: Text
                      name: text1
                      props:
                        value: Enter org
                    - component: Text
                      name: text
                      layout:
                        columnSize: 1
                      props:
                        value: Enter repository
                - component: PageColumn
                  name: pageColumn2
                  layout:
                    columnSize: 1
                  children:
                    - component: TextField
                      name: org
                      props:
                        defaultValue: mui
                    - component: TextField
                      name: repo
                      layout:
                        columnSize: 1
                        horizontalAlign: start
                        verticalAlign: center
                      props:
                        defaultValue: mui-toolpad
        - component: Metric
          name: metric1
          layout:
            columnSize: 1
          props:
            value:
              $$jsExpression: |
                queryStargazers.data.repository.stargazerCount
            label: Stargazers Count
            fullWidth: true
    - component: Text
      name: text2
      layout:
        columnSize: 1
        horizontalAlign: center
        verticalAlign: center
      props:
        value: ⭐️ ⭐️ ⭐️ Most recent 100 Stargazers ⭐️ ⭐️ ⭐️
        variant: h6
    - component: DataGrid
      name: dataGrid
      layout:
        columnSize: 1
        height: 540
      props:
        rows:
          $$jsExpression: |
            queryStargazers.data.repository.stargazers.nodes.map((node) => ({
              ...node,
              followers: node.followersCount.totalCount,
            }))
        columns:
          - field: name
            type: string
          - field: email
            type: string
          - field: company
            type: json
          - field: location
            type: json
          - field: bio
            type: string
            width: 215
          - field: url
            type: link
            width: 136
          - field: followers
            type: number
            width: 86
          - field: createdAt
            type: string
        height: 572
  queries:
    - name: queryStargazers
      query:
        function: function.ts#queryStargazers
        kind: local
      parameters:
        - name: owner
          value:
            $$jsExpression: |
              org.value
        - name: repository
          value:
            $$jsExpression: |
              repo.value
