apiVersion: v1
kind: page
spec:
  title: Google sheets
  queries:
    - name: fetchSheet
      query:
        function: fetchSheet
        kind: local
      parameters:
        - name: spreadsheetId
          value:
            $$jsExpression: |
              select.value
        - name: range
          value:
            $$jsExpression: |
              textField.value
    - name: fetchList
      query:
        function: functions.ts#fetchList
        kind: local
      parameters:
        - name: spreadsheetId
          value:
            $$jsExpression: |
              select.value
        - name: range
          value:
            $$jsExpression: |
              textField.value
  content:
    - component: PageRow
      name: pageRow1
      children:
        - component: Select
          name: select
          props:
            label: Choose Spreadsheet
            fullWidth: true
            options:
              $$jsExpression: |
                fetchList.data.map((a) => a.id)
          layout:
            columnSize: 1
        - component: TextField
          name: textField
          props:
            defaultValue: Sheet1!A:Z
            label: Enter range
            fullWidth: true
    - component: PageRow
      name: pageRow
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                fetchSheet.data
            columns:
              - field: Month
                type: string
              - field: Number of days
                type: string
            height: 622
