coverage:
  ignore:
    - '*/icons/*'
    # deprecated Toolpad Studio:
    - 'packages/toolpad-studio/*'
    - 'packages/toolpad-studio-runtime/*'
    - 'packages/toolpad-studio-components/*'
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch: off
comment: false
