packages:
  - 'packages/*'
  - 'playground/*'
  - 'docs'
  - 'examples/core/crud-nextjs'
  - 'examples/core/crud-nextjs-pages'
  # deprecated Toolpad Studio:
  - '!packages/toolpad-studio'
  - '!packages/toolpad-studio-runtime'
  - '!packages/toolpad-studio-components'
