apiVersion: v1
kind: page
spec:
  title: Prisma example
  content:
    - component: PageRow
      name: pageRow1
      children:
        - component: Text
          name: text
          layout:
            horizontalAlign: start
          props:
            variant: h2
            value: Users
            mode: text
    - component: PageRow
      name: pageRow2
      children:
        - component: Button
          name: deleteButton
          props:
            content: Delete
            disabled:
              $$jsExpression: |
                !usersDataGrid.selection
            onClick:
              $$jsExpressionAction: |-
                await deleteUser.fetch()
                getUsers.refetch()
    - component: PageRow
      name: pageRow
      children:
        - component: DataGrid
          name: usersDataGrid
          props:
            rows:
              $$jsExpression: |
                getUsers.data
            columns:
              - field: id
                type: number
                width: 77
              - field: name
                type: string
                width: 120
              - field: email
                type: string
                width: 335
            height: 296
    - component: PageRow
      name: pageRow3
      children:
        - component: Form
          name: addUserForm
          props:
            submitButtonText: Add user
            onSubmit:
              $$jsExpressionAction: |-
                await addUser.fetch()
                getUsers.refetch()
          children:
            - component: PageRow
              name: pageRow4
              children:
                - component: TextField
                  name: textField
                  props:
                    name: name
                    label: Name
                    fullWidth: true
                    isRequired: true
                - component: TextField
                  name: textField1
                  props:
                    name: email
                    label: Email
                    fullWidth: true
                    isRequired: true
  queries:
    - name: getUsers
      query:
        function: getUsers
        kind: local
      parameters:
        - name: name
          value: Charlie
        - name: email
          value: charlie@mui.com
    - name: addUser
      mode: mutation
      query:
        function: addUser
        kind: local
      parameters:
        - name: user
          value:
            $$jsExpression: |
              addUserForm.value
    - name: deleteUser
      mode: mutation
      query:
        function: deleteUser
        kind: local
      parameters:
        - name: id
          value:
            $$jsExpression: |
              usersDataGrid.selection?.id
