apiVersion: v1
kind: page
spec:
  title: page2
  content:
    - component: PageRow
      name: pageRow2
      children:
        - component: Button
          name: button1
          props:
            color: secondary
            variant: outlined
            size: medium
            content: Refresh
            sx: {}
            onClick:
              $$jsExpressionAction: getOrders.refetch()
            loading:
              $$jsExpression: |
                getCustomers.isLoading || getCustomers.isFetching
    - component: PageRow
      name: pageRow1
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                getOrders.data
            columns:
              - field: ID
                type: string
                valueGetter: null
              - field: OrderID
                type: codeComponent
                valueGetter: null
                codeComponent: OrderIdChip
              - field: Avatar
                type: image
                valueGetter: null
              - field: Name
                type: string
                valueGetter: null
                editable: true
              - field: Profile
                type: link
                valueGetter: null
                width: 222
              - field: Amount
                type: string
                valueGetter: null
                editable: true
              - field: PurchaseDate
                type: number
                valueGetter: null
                width: 218
            loading:
              $$jsExpression: |
                getOrders.isLoading || getOrders.isFetching
    - component: PageRow
      name: pageRow6
      children:
        - component: Button
          name: button2
          props:
            color: secondary
            content: Delete Order
            loading:
              $$jsExpression: |
                deleteOrder.isLoading || deleteOrder.isFetching
            disabled: false
            onClick:
              $$jsExpressionAction: deleteOrder.call()
            sx:
              $$jsExpression: |-
                {
                  "display": dataGrid?.selection ? 'block' : 'none'
                }
            variant: contained
            size: medium
    - component: PageRow
      name: pageRow7
      children:
        - component: Container
          name: container
          children:
            - component: PageRow
              name: pageRow8
              children:
                - component: PageColumn
                  name: pageColumn1
                  layout:
                    columnSize: 1
                  children:
                    - component: Text
                      name: text
                      layout:
                        horizontalAlign: center
                      props:
                        variant: h6
                        value: Add New Order
                        mode: text
                        sx:
                          textAlign: center
                          color: '#999'
                    - component: Form
                      name: form
                      props:
                        hasResetButton: false
                        formControlsAlign: start
                        sx:
                          gap: 2
                        onSubmit:
                          $$jsExpressionAction: createCustomer.call()
                        formControlsFullWidth: true
                      children:
                        - component: PageRow
                          name: pageRow3
                          children:
                            - component: PageColumn
                              name: pageColumn
                              layout:
                                columnSize: 1
                              children:
                                - component: PageRow
                                  name: pageRow5
                                  props:
                                    justifyContent: start
                                  children:
                                    - component: TextField
                                      name: textField1
                                      layout:
                                        columnSize: 0.6522842639593909
                                        horizontalAlign: start
                                      props:
                                        name: OrderID
                                        defaultValue:
                                          $$jsExpression: |
                                            getUUID.data || ""
                                        disabled: true
                                        label: Order ID
                                    - component: Button
                                      name: button
                                      layout:
                                        columnSize: 1.3477157360406091
                                        horizontalAlign: start
                                      props:
                                        variant: outlined
                                        content: Create UUID
                                        onClick:
                                          $$jsExpressionAction: getUUID.call()
                                        color: secondary
                                        size: medium
                                - component: TextField
                                  name: textField
                                  layout:
                                    horizontalAlign: start
                                  props:
                                    name: Name
                                    label: Name
                                    variant: outlined
                                - component: TextField
                                  name: textField2
                                  layout:
                                    horizontalAlign: start
                                  props:
                                    name: Amount
                                    label: Amount
                                - component: DatePicker
                                  name: datePicker
                                  props:
                                    name: PurchaseDate
                                    label: Purchase Date
          props:
            sx:
              padding: 1
              border: 'solid 2px #CCC'
            visible:
              $$jsExpression: |
                Boolean(dataGrid.selection && false)
  queries:
    - name: getOrders
      query:
        kind: rest
        url: https://635aaf68aa7c3f113daceeef.mockapi.io/customers
        searchParams: []
        headers: []
        method: GET
    - name: getUUID
      mode: mutation
      query:
        function: createNewUUID
        kind: local
    - name: deleteOrder
      mode: mutation
      query:
        kind: rest
        url:
          $$jsExpression: >
            `https://635aaf68aa7c3f113daceeef.mockapi.io/customers/${parameters.id}`
        searchParams: []
        headers: []
        method: DELETE
      parameters:
        - name: id
          value:
            $$jsExpression: |
              dataGrid.selection?.["ID"]
  display: shell
