type ExportMapValue = Promise<any>;

const muiMaterialExports = new Map<string, ExportMapValue>([
  ['@mui/material', import('@mui/material')],
  ['@mui/material/Accordion', import('@mui/material/Accordion')],
  ['@mui/material/CssBaseline', import('@mui/material/CssBaseline')],
  ['@mui/material/List', import('@mui/material/List')],
  ['@mui/material/Snackbar', import('@mui/material/Snackbar')],
  ['@mui/material/ToggleButtonGroup', import('@mui/material/ToggleButtonGroup')],
  ['@mui/material/AccordionActions', import('@mui/material/AccordionActions')],
  ['@mui/material/Dialog', import('@mui/material/Dialog')],
  ['@mui/material/ListItem', import('@mui/material/ListItem')],
  ['@mui/material/SnackbarContent', import('@mui/material/SnackbarContent')],
  ['@mui/material/Toolbar', import('@mui/material/Toolbar')],
  ['@mui/material/AccordionDetails', import('@mui/material/AccordionDetails')],
  ['@mui/material/DialogActions', import('@mui/material/DialogActions')],
  ['@mui/material/ListItemAvatar', import('@mui/material/ListItemAvatar')],
  ['@mui/material/SpeedDial', import('@mui/material/SpeedDial')],
  ['@mui/material/Tooltip', import('@mui/material/Tooltip')],
  ['@mui/material/AccordionSummary', import('@mui/material/AccordionSummary')],
  ['@mui/material/DialogContent', import('@mui/material/DialogContent')],
  ['@mui/material/ListItemButton', import('@mui/material/ListItemButton')],
  ['@mui/material/SpeedDialAction', import('@mui/material/SpeedDialAction')],
  ['@mui/material/Typography', import('@mui/material/Typography')],
  ['@mui/material/Alert', import('@mui/material/Alert')],
  ['@mui/material/DialogContentText', import('@mui/material/DialogContentText')],
  ['@mui/material/ListItemIcon', import('@mui/material/ListItemIcon')],
  ['@mui/material/SpeedDialIcon', import('@mui/material/SpeedDialIcon')],
  ['@mui/material/Unstable_Grid2', import('@mui/material/Unstable_Grid2')],
  ['@mui/material/AlertTitle', import('@mui/material/AlertTitle')],
  ['@mui/material/DialogTitle', import('@mui/material/DialogTitle')],
  ['@mui/material/ListItemSecondaryAction', import('@mui/material/ListItemSecondaryAction')],
  ['@mui/material/Stack', import('@mui/material/Stack')],
  ['@mui/material/Unstable_TrapFocus', import('@mui/material/Unstable_TrapFocus')],
  ['@mui/material/AppBar', import('@mui/material/AppBar')],
  ['@mui/material/Divider', import('@mui/material/Divider')],
  ['@mui/material/ListItemText', import('@mui/material/ListItemText')],
  ['@mui/material/Step', import('@mui/material/Step')],
  ['@mui/material/Zoom', import('@mui/material/Zoom')],
  ['@mui/material/Autocomplete', import('@mui/material/Autocomplete')],
  ['@mui/material/Drawer', import('@mui/material/Drawer')],
  ['@mui/material/ListSubheader', import('@mui/material/ListSubheader')],
  ['@mui/material/StepButton', import('@mui/material/StepButton')],
  ['@mui/material/className', import('@mui/material/className')],
  ['@mui/material/Avatar', import('@mui/material/Avatar')],
  ['@mui/material/Fab', import('@mui/material/Fab')],
  ['@mui/material/Menu', import('@mui/material/Menu')],
  ['@mui/material/StepConnector', import('@mui/material/StepConnector')],
  ['@mui/material/colors', import('@mui/material/colors')],
  ['@mui/material/AvatarGroup', import('@mui/material/AvatarGroup')],
  ['@mui/material/Fade', import('@mui/material/Fade')],
  ['@mui/material/MenuItem', import('@mui/material/MenuItem')],
  ['@mui/material/StepContent', import('@mui/material/StepContent')],
  ['@mui/material/darkScrollbar', import('@mui/material/darkScrollbar')],
  ['@mui/material/Backdrop', import('@mui/material/Backdrop')],
  ['@mui/material/FilledInput', import('@mui/material/FilledInput')],
  ['@mui/material/MenuList', import('@mui/material/MenuList')],
  ['@mui/material/StepIcon', import('@mui/material/StepIcon')],
  ['@mui/material/Badge', import('@mui/material/Badge')],
  ['@mui/material/FormControl', import('@mui/material/FormControl')],
  ['@mui/material/MobileStepper', import('@mui/material/MobileStepper')],
  ['@mui/material/StepLabel', import('@mui/material/StepLabel')],
  ['@mui/material/BottomNavigation', import('@mui/material/BottomNavigation')],
  ['@mui/material/FormControlLabel', import('@mui/material/FormControlLabel')],
  ['@mui/material/Modal', import('@mui/material/Modal')],
  ['@mui/material/Stepper', import('@mui/material/Stepper')],
  ['@mui/material/BottomNavigationAction', import('@mui/material/BottomNavigationAction')],
  ['@mui/material/FormGroup', import('@mui/material/FormGroup')],
  ['@mui/material/NativeSelect', import('@mui/material/NativeSelect')],
  ['@mui/material/StyledEngineProvider', import('@mui/material/StyledEngineProvider')],
  ['@mui/material/Box', import('@mui/material/Box')],
  ['@mui/material/FormHelperText', import('@mui/material/FormHelperText')],
  ['@mui/material/NoSsr', import('@mui/material/NoSsr')],
  ['@mui/material/SvgIcon', import('@mui/material/SvgIcon')],
  ['@mui/material/locale', import('@mui/material/locale')],
  ['@mui/material/Breadcrumbs', import('@mui/material/Breadcrumbs')],
  ['@mui/material/FormLabel', import('@mui/material/FormLabel')],
  ['@mui/material/OutlinedInput', import('@mui/material/OutlinedInput')],
  ['@mui/material/SwipeableDrawer', import('@mui/material/SwipeableDrawer')],
  ['@mui/material/Button', import('@mui/material/Button')],
  ['@mui/material/GlobalStyles', import('@mui/material/GlobalStyles')],
  ['@mui/material/Switch', import('@mui/material/Switch')],
  ['@mui/material/ButtonBase', import('@mui/material/ButtonBase')],
  ['@mui/material/Grid', import('@mui/material/Grid')],
  ['@mui/material/Pagination', import('@mui/material/Pagination')],
  ['@mui/material/Tab', import('@mui/material/Tab')],
  ['@mui/material/ButtonGroup', import('@mui/material/ButtonGroup')],
  ['@mui/material/Grow', import('@mui/material/Grow')],
  ['@mui/material/PaginationItem', import('@mui/material/PaginationItem')],
  ['@mui/material/TabScrollButton', import('@mui/material/TabScrollButton')],
  ['@mui/material/Hidden', import('@mui/material/Hidden')],
  ['@mui/material/Paper', import('@mui/material/Paper')],
  ['@mui/material/Table', import('@mui/material/Table')],
  ['@mui/material/styles', import('@mui/material/styles')],
  ['@mui/material/Card', import('@mui/material/Card')],
  ['@mui/material/Icon', import('@mui/material/Icon')],
  ['@mui/material/Popover', import('@mui/material/Popover')],
  ['@mui/material/TableBody', import('@mui/material/TableBody')],
  ['@mui/material/CardActionArea', import('@mui/material/CardActionArea')],
  ['@mui/material/IconButton', import('@mui/material/IconButton')],
  ['@mui/material/Popper', import('@mui/material/Popper')],
  ['@mui/material/TableCell', import('@mui/material/TableCell')],
  ['@mui/material/transitions', import('@mui/material/transitions')],
  ['@mui/material/CardActions', import('@mui/material/CardActions')],
  ['@mui/material/ImageList', import('@mui/material/ImageList')],
  ['@mui/material/Portal', import('@mui/material/Portal')],
  ['@mui/material/TableContainer', import('@mui/material/TableContainer')],
  ['@mui/material/CardContent', import('@mui/material/CardContent')],
  ['@mui/material/ImageListItem', import('@mui/material/ImageListItem')],
  ['@mui/material/TableFooter', import('@mui/material/TableFooter')],
  ['@mui/material/useAutocomplete', import('@mui/material/useAutocomplete')],
  ['@mui/material/CardHeader', import('@mui/material/CardHeader')],
  ['@mui/material/ImageListItemBar', import('@mui/material/ImageListItemBar')],
  ['@mui/material/Radio', import('@mui/material/Radio')],
  ['@mui/material/TableHead', import('@mui/material/TableHead')],
  ['@mui/material/useMediaQuery', import('@mui/material/useMediaQuery')],
  ['@mui/material/CardMedia', import('@mui/material/CardMedia')],
  ['@mui/material/Input', import('@mui/material/Input')],
  ['@mui/material/RadioGroup', import('@mui/material/RadioGroup')],
  ['@mui/material/TablePagination', import('@mui/material/TablePagination')],
  ['@mui/material/usePagination', import('@mui/material/usePagination')],
  ['@mui/material/Checkbox', import('@mui/material/Checkbox')],
  ['@mui/material/InputAdornment', import('@mui/material/InputAdornment')],
  ['@mui/material/Rating', import('@mui/material/Rating')],
  ['@mui/material/TableRow', import('@mui/material/TableRow')],
  ['@mui/material/useScrollTrigger', import('@mui/material/useScrollTrigger')],
  ['@mui/material/Chip', import('@mui/material/Chip')],
  ['@mui/material/InputBase', import('@mui/material/InputBase')],
  ['@mui/material/ScopedCssBaseline', import('@mui/material/ScopedCssBaseline')],
  ['@mui/material/TableSortLabel', import('@mui/material/TableSortLabel')],
  ['@mui/material/useTouchRipple', import('@mui/material/useTouchRipple')],
  ['@mui/material/CircularProgress', import('@mui/material/CircularProgress')],
  ['@mui/material/InputLabel', import('@mui/material/InputLabel')],
  ['@mui/material/Select', import('@mui/material/Select')],
  ['@mui/material/Tabs', import('@mui/material/Tabs')],
  ['@mui/material/utils', import('@mui/material/utils')],
  ['@mui/material/ClickAwayListener', import('@mui/material/ClickAwayListener')],
  ['@mui/material/Skeleton', import('@mui/material/Skeleton')],
  ['@mui/material/TextField', import('@mui/material/TextField')],
  ['@mui/material/Collapse', import('@mui/material/Collapse')],
  ['@mui/material/LinearProgress', import('@mui/material/LinearProgress')],
  ['@mui/material/Slide', import('@mui/material/Slide')],
  ['@mui/material/TextareaAutosize', import('@mui/material/TextareaAutosize')],
  ['@mui/material/Container', import('@mui/material/Container')],
  ['@mui/material/Link', import('@mui/material/Link')],
  ['@mui/material/Slider', import('@mui/material/Slider')],
  ['@mui/material/ToggleButton', import('@mui/material/ToggleButton')],
]);

const muiDatePickersExports = new Map<string, ExportMapValue>([
  ['@mui/x-date-pickers', import('@mui/x-date-pickers')],
  // ['@mui/x-date-pickers/AdapterDateFns', import('@mui/x-date-pickers/AdapterDateFns')],
  [
    '@mui/x-date-pickers/CalendarPickerSkeleton',
    import('@mui/x-date-pickers/CalendarPickerSkeleton'),
  ],
  ['@mui/x-date-pickers/DesktopTimePicker', import('@mui/x-date-pickers/DesktopTimePicker')],
  ['@mui/x-date-pickers/MonthPicker', import('@mui/x-date-pickers/MonthPicker')],
  ['@mui/x-date-pickers/StaticTimePicker', import('@mui/x-date-pickers/StaticTimePicker')],
  ['@mui/x-date-pickers/AdapterDayjs', import('@mui/x-date-pickers/AdapterDayjs')],
  ['@mui/x-date-pickers/ClockPicker', import('@mui/x-date-pickers/ClockPicker')],
  ['@mui/x-date-pickers/PickersActionBar', import('@mui/x-date-pickers/PickersActionBar')],
  ['@mui/x-date-pickers/TimePicker', import('@mui/x-date-pickers/TimePicker')],
  ['@mui/x-date-pickers/locales', import('@mui/x-date-pickers/locales')],
  // ['@mui/x-date-pickers/AdapterLuxon', import('@mui/x-date-pickers/AdapterLuxon')],
  ['@mui/x-date-pickers/DatePicker', import('@mui/x-date-pickers/DatePicker')],
  ['@mui/x-date-pickers/LocalizationProvider', import('@mui/x-date-pickers/LocalizationProvider')],
  ['@mui/x-date-pickers/PickersDay', import('@mui/x-date-pickers/PickersDay')],
  ['@mui/x-date-pickers/YearPicker', import('@mui/x-date-pickers/YearPicker')],
  // ['@mui/x-date-pickers/AdapterMoment', import('@mui/x-date-pickers/AdapterMoment')],
  ['@mui/x-date-pickers/DateTimePicker', import('@mui/x-date-pickers/DateTimePicker')],
  ['@mui/x-date-pickers/MobileDatePicker', import('@mui/x-date-pickers/MobileDatePicker')],
  ['@mui/x-date-pickers/DesktopDatePicker', import('@mui/x-date-pickers/DesktopDatePicker')],
  ['@mui/x-date-pickers/MobileDateTimePicker', import('@mui/x-date-pickers/MobileDateTimePicker')],
  ['@mui/x-date-pickers/StaticDatePicker', import('@mui/x-date-pickers/StaticDatePicker')],
  ['@mui/x-date-pickers/CalendarPicker', import('@mui/x-date-pickers/CalendarPicker')],
  [
    '@mui/x-date-pickers/DesktopDateTimePicker',
    import('@mui/x-date-pickers/DesktopDateTimePicker'),
  ],
  ['@mui/x-date-pickers/MobileTimePicker', import('@mui/x-date-pickers/MobileTimePicker')],
  ['@mui/x-date-pickers/StaticDateTimePicker', import('@mui/x-date-pickers/StaticDateTimePicker')],
]);

const muiDatePickersProExports = new Map<string, ExportMapValue>([
  ['@mui/x-date-pickers-pro', import('@mui/x-date-pickers-pro')],
  // ['@mui/x-date-pickers-pro/AdapterDateFns', import('@mui/x-date-pickers-pro/AdapterDateFns')],
  ['@mui/x-date-pickers-pro/DateRangePicker', import('@mui/x-date-pickers-pro/DateRangePicker')],
  [
    '@mui/x-date-pickers-pro/MultiInputDateRangeField',
    import('@mui/x-date-pickers-pro/MultiInputDateRangeField'),
  ],
  ['@mui/x-date-pickers-pro/AdapterDayjs', import('@mui/x-date-pickers-pro/AdapterDayjs')],
  [
    '@mui/x-date-pickers-pro/DateRangePickerDay',
    import('@mui/x-date-pickers-pro/DateRangePickerDay'),
  ],
  ['@mui/x-date-pickers-pro/package.json', import('@mui/x-date-pickers-pro/package.json')],
  // ['@mui/x-date-pickers-pro/AdapterLuxon', import('@mui/x-date-pickers-pro/AdapterLuxon')],
  [
    '@mui/x-date-pickers-pro/DesktopDateRangePicker',
    import('@mui/x-date-pickers-pro/DesktopDateRangePicker'),
  ],
  [
    '@mui/x-date-pickers-pro/SingleInputDateRangeField',
    import('@mui/x-date-pickers-pro/SingleInputDateRangeField'),
  ],
  // ['@mui/x-date-pickers-pro/AdapterMoment', import('@mui/x-date-pickers-pro/AdapterMoment')],
  [
    '@mui/x-date-pickers-pro/StaticDateRangePicker',
    import('@mui/x-date-pickers-pro/StaticDateRangePicker'),
  ],
  [
    '@mui/x-date-pickers-pro/MobileDateRangePicker',
    import('@mui/x-date-pickers-pro/MobileDateRangePicker'),
  ],
]);

export default new Map([
  ...muiMaterialExports,
  ...muiDatePickersExports,
  ...muiDatePickersProExports,
]);
