# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.2.0/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  title: Charts
  content:
    - component: PageRow
      name: pageRow
      props:
        justifyContent: start
      children:
        - component: Chart
          name: chart
          props:
            data:
              - label: No. of movies released per year
                kind: line
                data:
                  $$jsExpression: |
                    query1.data.map((movie) => ({
                      year: movie.year,
                      count_id: query1.data.reduce((acc, currentMovie) => {
                        return currentMovie.year === movie.year ? acc + 1 : acc
                      }, 0),
                    }))
                color: '#f44336'
                xKey: year
                yKey: count_id
        - component: Chart
          name: chart1
          props:
            data:
              - label: No. of movies released per year
                kind: bar
                data:
                  $$jsExpression: |
                    query1.data.map((movie) => ({
                      year: movie.year,
                      count_id: query1.data.reduce((acc, currentMovie) => {
                        return currentMovie.year === movie.year ? acc + 1 : acc
                      }, 0),
                    }))
                color: '#673ab7'
                xKey: year
                yKey: count_id
    - component: Chart
      name: chart2
      props:
        data:
          - label: No. of movies released per year
            kind: area
            data:
              $$jsExpression: |
                query1.data.map((movie) => ({
                  year: movie.year,
                  count_id: query1.data.reduce((acc, currentMovie) => {
                    return currentMovie.year === movie.year ? acc + 1 : acc
                  }, 0),
                }))
            color: '#00bcd4'
            xKey: year
            yKey: count_id
      layout:
        columnSize: 1
    - component: Chart
      name: chart3
      props:
        data:
          - label: No. of movies released per year
            kind: scatter
            data:
              $$jsExpression: |
                query1.data.map((movie) => ({
                  year: Number(movie.year),
                  count_id: query1.data.reduce((acc, currentMovie) => {
                    return currentMovie.year === movie.year ? acc + 1 : acc
                  }, 0),
                }))
            color: '#4caf50'
            xKey: year
            yKey: count_id
  queries:
    - name: query1
      query:
        kind: rest
        headers: []
        method: GET
        transform: return data.movies;
        transformEnabled: true
        searchParams: []
        url: https://raw.githubusercontent.com/mui/toolpad/master/public/movies.json
  display: shell
