version: '3.7'

services:
  toolpad:
    image: muicom/toolpad:${TAG:-latest}
    environment:
      - TOOLPAD_DATABASE_URL=postgresql://toolpad-app:secretpw@postgres:5432/postgres?connect_timeout=10
      - PORT=3000
      - EXTERNAL_URL=http://localhost:3000/
    ports:
      - '3000:3000'

  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=toolpad-app
      - POSTGRES_PASSWORD=secretpw
    logging:
      options:
        max-size: 10m
        max-file: '3'
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
